/** Optometry/ophthalmology ICD-10-CM subset for exam diagnosis lookup. */

export type Icd10Entry = { code: string; description: string };

function ou(
  right: string,
  left: string,
  both: string,
  name: string,
): Icd10Entry[] {
  return [
    { code: right, description: `${name}, right eye` },
    { code: left, description: `${name}, left eye` },
    { code: both, description: `${name}, bilateral` },
  ];
}

export const ICD10_OPTOMETRY: Icd10Entry[] = [
  // Refractive (H52)
  ...ou('H52.01', 'H52.02', 'H52.03', 'Hypermetropia'),
  ...ou('H52.11', 'H52.12', 'H52.13', 'Myopia'),
  ...ou('H52.201', 'H52.202', 'H52.203', 'Unspecified astigmatism'),
  ...ou('H52.211', 'H52.212', 'H52.213', 'Irregular astigmatism'),
  ...ou('H52.221', 'H52.222', 'H52.223', 'Regular astigmatism'),
  { code: 'H52.31', description: 'Anisometropia' },
  { code: 'H52.32', description: 'Aniseikonia' },
  { code: 'H52.4', description: 'Presbyopia' },
  { code: 'H52.511', description: 'Internal ophthalmoplegia, right eye' },
  { code: 'H52.512', description: 'Internal ophthalmoplegia, left eye' },
  { code: 'H52.513', description: 'Internal ophthalmoplegia, bilateral' },
  { code: 'H52.6', description: 'Other disorders of refraction' },
  { code: 'H52.7', description: 'Unspecified disorder of refraction' },

  // Dry eye / lacrimal (H04)
  ...ou('H04.121', 'H04.122', 'H04.123', 'Dry eye syndrome of lacrimal glands'),
  ...ou('H04.131', 'H04.132', 'H04.133', 'Lacrimal gland cyst'),
  { code: 'H04.201', description: 'Unspecified epiphora, right side' },
  { code: 'H04.202', description: 'Unspecified epiphora, left side' },
  { code: 'H04.203', description: 'Unspecified epiphora, bilateral' },

  // Lids / blepharitis (H01, H02)
  { code: 'H01.001', description: 'Unspecified blepharitis, right upper eyelid' },
  { code: 'H01.002', description: 'Unspecified blepharitis, right lower eyelid' },
  { code: 'H01.003', description: 'Unspecified blepharitis, right eye, unspecified eyelid' },
  { code: 'H01.004', description: 'Unspecified blepharitis, left upper eyelid' },
  { code: 'H01.005', description: 'Unspecified blepharitis, left lower eyelid' },
  { code: 'H01.006', description: 'Unspecified blepharitis, left eye, unspecified eyelid' },
  { code: 'H01.00A', description: 'Unspecified blepharitis, right eye, upper and lower eyelids' },
  { code: 'H01.00B', description: 'Unspecified blepharitis, left eye, upper and lower eyelids' },
  { code: 'H01.011', description: 'Ulcerative blepharitis, right upper eyelid' },
  { code: 'H01.014', description: 'Ulcerative blepharitis, left upper eyelid' },
  { code: 'H01.021', description: 'Squamous blepharitis, right upper eyelid' },
  { code: 'H01.024', description: 'Squamous blepharitis, left upper eyelid' },
  { code: 'H02.001', description: 'Unspecified entropion of right upper eyelid' },
  { code: 'H02.004', description: 'Unspecified entropion of left upper eyelid' },
  { code: 'H02.101', description: 'Unspecified ectropion of right upper eyelid' },
  { code: 'H02.104', description: 'Unspecified ectropion of left upper eyelid' },
  { code: 'H02.401', description: 'Unspecified ptosis of right eyelid' },
  { code: 'H02.402', description: 'Unspecified ptosis of left eyelid' },
  { code: 'H02.403', description: 'Unspecified ptosis of bilateral eyelids' },
  { code: 'H02.831', description: 'Dermatochalasis of right upper eyelid' },
  { code: 'H02.834', description: 'Dermatochalasis of left upper eyelid' },
  { code: 'H02.89', description: 'Other specified disorders of eyelid' },

  // Conjunctiva (H10, H11)
  ...ou('H10.011', 'H10.012', 'H10.013', 'Acute follicular conjunctivitis'),
  ...ou('H10.021', 'H10.022', 'H10.023', 'Other mucopurulent conjunctivitis'),
  ...ou('H10.31', 'H10.32', 'H10.33', 'Unspecified acute conjunctivitis'),
  ...ou('H10.401', 'H10.402', 'H10.403', 'Unspecified chronic conjunctivitis'),
  { code: 'H10.45', description: 'Other chronic allergic conjunctivitis' },
  ...ou('H11.001', 'H11.002', 'H11.003', 'Unspecified pterygium'),
  ...ou('H11.151', 'H11.152', 'H11.153', 'Pinguecula'),

  // Cornea (H16, H18)
  ...ou('H16.001', 'H16.002', 'H16.003', 'Unspecified corneal ulcer'),
  ...ou('H16.111', 'H16.112', 'H16.113', 'Macular keratitis'),
  ...ou('H16.141', 'H16.142', 'H16.143', 'Punctate keratitis'),
  ...ou('H16.221', 'H16.222', 'H16.223', 'Keratoconjunctivitis sicca, not specified as Sjögren'),
  { code: 'H18.001', description: 'Unspecified corneal deposit, right eye' },
  { code: 'H18.002', description: 'Unspecified corneal deposit, left eye' },
  { code: 'H18.003', description: 'Unspecified corneal deposit, bilateral' },
  ...ou('H18.601', 'H18.602', 'H18.603', 'Keratoconus, unspecified'),
  ...ou('H18.611', 'H18.612', 'H18.613', 'Keratoconus, stable'),
  ...ou('H18.621', 'H18.622', 'H18.623', 'Keratoconus, unstable'),

  // Cataract (H25, H26)
  ...ou('H25.011', 'H25.012', 'H25.013', 'Cortical age-related cataract'),
  ...ou('H25.11', 'H25.12', 'H25.13', 'Age-related nuclear cataract'),
  ...ou('H25.031', 'H25.032', 'H25.033', 'Anterior subcapsular polar age-related cataract'),
  ...ou('H25.041', 'H25.042', 'H25.043', 'Posterior subcapsular polar age-related cataract'),
  ...ou('H25.811', 'H25.812', 'H25.813', 'Combined forms of age-related cataract'),
  { code: 'H25.9', description: 'Unspecified age-related cataract' },
  ...ou('H26.001', 'H26.002', 'H26.003', 'Unspecified infantile and juvenile cataract'),
  ...ou('H26.491', 'H26.492', 'H26.493', 'Other secondary cataract'),
  { code: 'H27.01', description: 'Aphakia, right eye' },
  { code: 'H27.02', description: 'Aphakia, left eye' },
  { code: 'H27.03', description: 'Aphakia, bilateral' },
  { code: 'Z96.1', description: 'Presence of intraocular lens' },

  // Glaucoma (H40)
  { code: 'H40.003', description: 'Preglaucoma, unspecified, bilateral' },
  { code: 'H40.011', description: 'Open angle with borderline findings, low risk, right eye' },
  { code: 'H40.012', description: 'Open angle with borderline findings, low risk, left eye' },
  { code: 'H40.013', description: 'Open angle with borderline findings, low risk, bilateral' },
  { code: 'H40.021', description: 'Open angle with borderline findings, high risk, right eye' },
  { code: 'H40.022', description: 'Open angle with borderline findings, high risk, left eye' },
  { code: 'H40.023', description: 'Open angle with borderline findings, high risk, bilateral' },
  { code: 'H40.1111', description: 'Primary open-angle glaucoma, right eye, mild stage' },
  { code: 'H40.1112', description: 'Primary open-angle glaucoma, right eye, moderate stage' },
  { code: 'H40.1113', description: 'Primary open-angle glaucoma, right eye, severe stage' },
  { code: 'H40.1121', description: 'Primary open-angle glaucoma, left eye, mild stage' },
  { code: 'H40.1122', description: 'Primary open-angle glaucoma, left eye, moderate stage' },
  { code: 'H40.1123', description: 'Primary open-angle glaucoma, left eye, severe stage' },
  { code: 'H40.1131', description: 'Primary open-angle glaucoma, bilateral, mild stage' },
  { code: 'H40.1132', description: 'Primary open-angle glaucoma, bilateral, moderate stage' },
  { code: 'H40.1133', description: 'Primary open-angle glaucoma, bilateral, severe stage' },
  { code: 'H40.11X2', description: 'Primary open-angle glaucoma, moderate stage' },
  { code: 'H40.11X3', description: 'Primary open-angle glaucoma, severe stage' },
  { code: 'H40.10X0', description: 'Unspecified open-angle glaucoma, stage unspecified' },
  { code: 'H40.1311', description: 'Pigmentary glaucoma, right eye, mild stage' },
  { code: 'H40.1321', description: 'Pigmentary glaucoma, left eye, mild stage' },
  { code: 'H40.1331', description: 'Pigmentary glaucoma, bilateral, mild stage' },
  { code: 'H40.151', description: 'Residual stage of open-angle glaucoma, right eye' },
  { code: 'H40.152', description: 'Residual stage of open-angle glaucoma, left eye' },
  { code: 'H40.153', description: 'Residual stage of open-angle glaucoma, bilateral' },
  { code: 'H40.9', description: 'Unspecified glaucoma' },

  // Retina / AMD (H35)
  { code: 'H35.3110', description: 'Nonexudative AMD, right eye, stage unspecified' },
  { code: 'H35.3111', description: 'Nonexudative AMD, right eye, early dry stage' },
  { code: 'H35.3112', description: 'Nonexudative AMD, right eye, intermediate dry stage' },
  { code: 'H35.3113', description: 'Nonexudative AMD, right eye, advanced atrophic without subfoveal involvement' },
  { code: 'H35.3120', description: 'Nonexudative AMD, left eye, stage unspecified' },
  { code: 'H35.3121', description: 'Nonexudative AMD, left eye, early dry stage' },
  { code: 'H35.3122', description: 'Nonexudative AMD, left eye, intermediate dry stage' },
  { code: 'H35.3130', description: 'Nonexudative AMD, bilateral, stage unspecified' },
  { code: 'H35.3131', description: 'Nonexudative AMD, bilateral, early dry stage' },
  { code: 'H35.3132', description: 'Nonexudative AMD, bilateral, intermediate dry stage' },
  { code: 'H35.3210', description: 'Exudative AMD, right eye, stage unspecified' },
  { code: 'H35.3220', description: 'Exudative AMD, left eye, stage unspecified' },
  { code: 'H35.3230', description: 'Exudative AMD, bilateral, stage unspecified' },
  ...ou('H35.371', 'H35.372', 'H35.373', 'Puckering of macula'),
  ...ou('H35.411', 'H35.412', 'H35.413', 'Lattice degeneration of retina'),
  { code: 'H35.81', description: 'Retinal edema' },
  { code: 'H35.89', description: 'Other specified retinal disorders' },
  { code: 'H43.391', description: 'Other vitreous opacities, right eye' },
  { code: 'H43.392', description: 'Other vitreous opacities, left eye' },
  { code: 'H43.393', description: 'Other vitreous opacities, bilateral' },
  { code: 'H43.811', description: 'Vitreous degeneration, right eye' },
  { code: 'H43.812', description: 'Vitreous degeneration, left eye' },
  { code: 'H43.813', description: 'Vitreous degeneration, bilateral' },

  // Diabetic retinopathy (E11.3)
  { code: 'E11.319', description: 'Type 2 diabetes mellitus with unspecified diabetic retinopathy without macular edema' },
  { code: 'E11.311', description: 'Type 2 diabetes mellitus with unspecified diabetic retinopathy with macular edema' },
  { code: 'E11.329', description: 'Type 2 DM with mild nonproliferative diabetic retinopathy without macular edema' },
  { code: 'E11.321', description: 'Type 2 DM with mild NPDR with macular edema' },
  { code: 'E11.339', description: 'Type 2 DM with moderate NPDR without macular edema' },
  { code: 'E11.331', description: 'Type 2 DM with moderate NPDR with macular edema' },
  { code: 'E11.349', description: 'Type 2 DM with severe NPDR without macular edema' },
  { code: 'E11.359', description: 'Type 2 DM with proliferative diabetic retinopathy without macular edema' },
  { code: 'E11.36', description: 'Type 2 diabetes mellitus with diabetic cataract' },
  { code: 'E11.39', description: 'Type 2 diabetes mellitus with other diabetic ophthalmic complication' },
  { code: 'E11.9', description: 'Type 2 diabetes mellitus without complications' },

  // Strabismus / binocular / amblyopia (H50, H53)
  { code: 'H50.00', description: 'Unspecified esotropia' },
  { code: 'H50.10', description: 'Unspecified exotropia' },
  { code: 'H50.111', description: 'Monocular exotropia, right eye' },
  { code: 'H50.112', description: 'Monocular exotropia, left eye' },
  { code: 'H50.18', description: 'Alternating exotropia' },
  { code: 'H50.2', description: 'Vertical strabismus' },
  { code: 'H50.21', description: 'Vertical strabismus, right eye' },
  { code: 'H50.22', description: 'Vertical strabismus, left eye' },
  { code: 'H50.31', description: 'Intermittent vertical strabismus' },
  { code: 'H50.311', description: 'Intermittent monocular esotropia, right eye' },
  { code: 'H50.312', description: 'Intermittent monocular esotropia, left eye' },
  { code: 'H53.001', description: 'Unspecified amblyopia, right eye' },
  { code: 'H53.002', description: 'Unspecified amblyopia, left eye' },
  { code: 'H53.003', description: 'Unspecified amblyopia, bilateral' },
  { code: 'H53.011', description: 'Deprivation amblyopia, right eye' },
  { code: 'H53.012', description: 'Deprivation amblyopia, left eye' },
  { code: 'H53.021', description: 'Refractive amblyopia, right eye' },
  { code: 'H53.022', description: 'Refractive amblyopia, left eye' },
  { code: 'H53.023', description: 'Refractive amblyopia, bilateral' },
  { code: 'H53.031', description: 'Strabismic amblyopia, right eye' },
  { code: 'H53.032', description: 'Strabismic amblyopia, left eye' },
  { code: 'H53.40', description: 'Unspecified visual field defects' },
  { code: 'H53.71', description: 'Glare sensitivity' },
  { code: 'H53.8', description: 'Other visual disturbances' },
  { code: 'H53.9', description: 'Unspecified visual disturbance' },

  // Optic nerve / other
  { code: 'H47.091', description: 'Other disorders of optic nerve, right eye' },
  { code: 'H47.092', description: 'Other disorders of optic nerve, left eye' },
  { code: 'H47.093', description: 'Other disorders of optic nerve, bilateral' },
  { code: 'H47.10', description: 'Unspecified papilledema' },
  { code: 'H47.20', description: 'Unspecified optic atrophy' },

  // Systemic with ocular relevance
  { code: 'I10', description: 'Essential (primary) hypertension' },
  { code: 'E78.5', description: 'Hyperlipidemia, unspecified' },
  { code: 'M35.00', description: "Sjögren syndrome, unspecified" },
  { code: 'G43.909', description: 'Migraine, unspecified, not intractable, without status migrainosus' },
  { code: 'Z79.899', description: 'Other long term (current) drug therapy' },
  { code: 'Z01.00', description: 'Encounter for examination of eyes and vision without abnormal findings' },
  { code: 'Z01.01', description: 'Encounter for examination of eyes and vision with abnormal findings' },
];
